services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "81:81"
      - "443:443"
      - "80:80"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

  contatos:
    build: .
    ports:
      - "8080:8080"
